platform/sensinact-system/src/main/java/org/eclipse/sensinact/gateway/system/invoker/Activator.java
platform/sensinact-system/src/test/java/org/eclipse/sensinact/gateway/system/test/TestSensiNactResource.java

This is a quick and dirty workaround for the fact that the sensiNact provider sometimes fails to register properly. The model management code needs a significant overhaul

Ensure that the sensinact-system provider is registered

---

platform/sensinact-core/src/main/java/org/eclipse/sensinact/gateway/core/method/AbstractAccessMethod.java
platform/sensinact-core/src/main/java/org/eclipse/sensinact/gateway/core/method/Shortcut.java
platform/sensinact-core/src/main/java/org/eclipse/sensinact/gateway/core/method/Signature.java

ACT methods were called based on Signature objects
shared between calls. As a result, parallel calls can
end up using both the parameters of one of them.
This commit prepares a new set of Parameter objects
when validating them, instead of storing the given
value into the ones of the shared Signature instance.

Make sure calls to ACT use given parameters

---

platform/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/sthbnd/http/factory/HttpMappingProtocolStackEndpointFactory.java
platform/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/sthbnd/http/factory/test/HttpDeviceFactoryTest.java
platform/southbound/http/http-device/src/main/java/org/eclipse/sensinact/gateway/sthbnd/http/smpl/SimpleHttpProtocolStackEndpoint.java

We can rely upon Declarative Services to correctly manage the lifecycle of our configurations
Also improve thread safety in the Http Device, and relax the timings in the unit tests

[HTTP Device Factory] Avoid directly implementing ManagedServiceFactory

---

distribution/template/sensinact

Allows to forward arguments to the script using quoted arguments, e.g. `sensinact "$*"`

Ignore empty arguments in sensinact start script

---

prototype/pom.xml

adds org.eclipse.dash plugin.
```
The Eclipse Dash License Tool identifies the licenses of content. It is intended primarily for use by Eclipse committers to vet third party content used by their Eclipse open source project.
```
docs:
`https://github.com/eclipse/dash-licenses/blob/master/README.md#maven-plugin-options`
command:
`mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES`
out:
```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (default-cli) @ sensinact-parent ---
[INFO] Querying Eclipse Foundation for license data for 67 items.
[INFO] Found 33 items.
[INFO] Querying ClearlyDefined for license data for 34 items.
[INFO] Found 34 items.
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] …
```

add org.eclipse.dash plugin

---

prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/Admin.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/Metadata.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/ModelMetadata.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/Provider.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/SensiNactFactory.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/SensiNactPackage.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/Service.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/configuration/SensiNactConfigurationComponent.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/configuration/SensiNactEPackageConfigurator.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/AdminImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/FeatureMetadataImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/MetadataImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/ModelMetadataImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/ProviderImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/SensiNactFactoryImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/SensiNactPackageImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/ServiceImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/impl/package-info.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/package-info.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/util/SensiNactAdapterFactory.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/util/SensiNactResourceFactoryImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/util/SensiNactResourceImpl.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/util/SensiNactSwitch.java
prototype/core/models/src/main/java/org/eclipse/sensinact/model/core/util/package-info.java
prototype/core/models/src/main/resources/model/sensinact.genmodel

generates a proper copyright header into generated sources
fyi @juergen-albert 
so the code will not change (empty copyright header) every time when a build happened

add copyright header into gen-model

---

.github/workflows/eclipse_ip.yml

Prevent Dash Errors for snapshot artifacts that we know to be safe.

Avoid scanning snapshot artifacts

---

prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactResource.java
prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/Coordinates.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactModelImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactResourceImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusImpl.java
prototype/core/models/src/main/resources/model/sensinact.ecore
prototype/core/models/src/main/resources/model/sensinact.genmodel

* Added an `extra` field to `Metadata`, allowing to add timestamped custom metadata to a resource
* `Resource.getValue()` now returns `TimedValue` to include its timestamp
* `SensiNactModelImpl.getResourceValue()` now reject null value type argument. Explicitly use `java.lang.Object` instead.
* GeoJson coordinates elevation is initialized to NaN to respect its documentation

Core update for SensorThings

---

prototype/northbound/sensorthings/dto/pom.xml
prototype/northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/Datastream.java
prototype/northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/FeatureOfInterest.java
prototype/northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/Location.java
prototype/northbound/sensorthings/dto/src/test/java/org/eclipse/sensinact/sensorthings/sensing/dto/JsonMappingTest.java
prototype/northbound/sensorthings/pom.xml
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/annotation/PropFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/annotation/RefFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/CountFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/ExpandFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/FilterFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/OrderByFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/PropFilterImpl.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/RefFilterImpl.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/SelectFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/SkipFilter.java
prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/TopFilter.java
prototype/northbound/sensorthings/rest.gateway/pom.xml
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DatastreamsAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DtoMapper.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/FeaturesOfInterestAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/HistoricalLocationsAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/LocationsAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ObservationsAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ObservedPropertiesAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/RootResourceAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/SensinactSensorthingsApplication.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/SensinactSessionProvider.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/SensorsAccessImpl.java
prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ThingsAccessImpl.java

* Use internal GeoJSON library
* Fixed filters behaviour when related argument is missing
* Don't use `@Context` to find the registered `ObjectMapper` and `SensinactSession` providers
* Normalized conversion of `admin/location` to a `GeoJsonObject`

Fixes on SensorThings

---

prototype/distribution/features/jakarta-rest-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartarest/InputStreamConsumer.java
prototype/distribution/features/jakarta-rest-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartarest/RestWhiteboardIntegrationTest.java
prototype/distribution/features/jakarta-servlet-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartaservlet/InputStreamConsumer.java
prototype/distribution/features/jakarta-servlet-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartaservlet/ServletWhiteboardIntegrationTest.java
prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/integration/FeatureLaunchingIntegrationTest.java
prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/integration/InputStreamConsumer.java

On Windows, some tests were failing as subprocesses were stuck.
This PR ensures that subprocesses output streams are flushed.
It might be interesting to create a specific module to share subprocess startup and streams consumption methods.

Fix launcher integration tests

---

prototype/distribution/features/jakarta-rest-whiteboard-feature/src/main/resources/jakarta-rest-whiteboard-feature.json
prototype/distribution/features/jakarta-servlet-whiteboard-feature/src/main/resources/jakarta-servlet-whiteboard-feature.json
prototype/distribution/features/northbound-rest-feature/src/main/resources/northbound-rest-feature.json
prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/FeatureLauncher.java
prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/FeatureLaunchingTest.java
prototype/distribution/launcher/src/test/resources/features/bad_depends_type.json
prototype/distribution/launcher/src/test/resources/features/need_fizz.json
prototype/distribution/launcher/src/test/resources/features/need_foo.json
prototype/distribution/launcher/src/test/resources/features/unknown_extension.json

Some features depend on other features. These commits make sure that we can express that dependency, and that the runtime requires the dependencies to be installed before the dependent feature is.

Add support for feature dependencies to the Feature Manager

---

prototype/distribution/launcher/export.bndrun
prototype/distribution/launcher/pom.xml
prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManagerTest.java
prototype/distribution/launcher/src/test/resources/configs/a/configuration.json
prototype/distribution/launcher/src/test/resources/configs/b/configuration-initial.json
prototype/distribution/launcher/src/test/resources/configs/b/configuration-update.json
prototype/pom.xml

Fixes a bug in the configuration watcher. Tests are slow on MacOS due to the lack of a native implementation in the JDK

Add more testing for the ConfigurationManager

---

prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/integration/session/AdminServiceTest.java

This change is required by any southbound provider that reuses the same timestamp to update admin resources.
We might want to have a better handling of timestamps on admin resources, possibly by providing a way to give multiple resources at once to update/create a provider.

Allow changing admin resource values when given timestamp equals current one

---

prototype/distribution/launcher/pom.xml

The bnd-export-maven-plugin provides a launcher, but as of 7.0.0 this requires Java 17. We therefore use 6.4.0 for this plugin to maintain compatibility with Java 11

Avoid using the bnd v7 launcher which needs Java 17

---

prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/EMFUtil.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/notification/impl/AbstractNotificationAccumulatorImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/notification/impl/ImmediateNotificationAccumulator.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/notification/impl/NotificationAccumulatorImpl.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/SubscriptionTest.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/DescriptionsTest.java
prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/FiltersTest.java

Note that this commit also:
* Fixes the set of supported types to include Instant via the SensinactPackage EInstant
* Adds a non-accumulating NotificationAccumulator instance for use when no command is running

Add a simple sensiNact provider representing the sensiNact instance

---

prototype/core/impl/integration-test.bndrun
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/EMFUtil.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/integration/session/AdminServiceTest.java
prototype/core/models/pom.xml
prototype/core/models/src/main/resources/model/sensinact.ecore
prototype/core/models/src/main/resources/model/sensinact.genmodel
prototype/northbound/rest/integration-test.bndrun
prototype/northbound/rest/pom.xml
prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/dto/CompleteProviderDescriptionDTO.java
prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/ResourceAccessTest.java
prototype/southbound/device-factory/parser-csv/src/test/java/org/eclipse/sensinact/gateway/southbound/device/parser/integration/csv/CSVParserTest.java
prototype/southbound/device-factory/parser-json/src/test/java/org/eclipse/sensinact/gateway/southbound/device/parser/integration/json/JSONParserTest.java
prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/HttpDeviceFactoryTest.java
prototype/southbound/mqtt/mqtt-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/factory/integration/MqttDeviceFactoryTest.java

The Admin service location resource should always be valid Geo Json. We can require this by using a GeoJsonObject as the type of the resource.

Require that admin/location is a GeoJsonObject

---

prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ModelBuilderImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ModelImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ResourceBuilderImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ServiceBuilderImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ServiceImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactDigitalTwinImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactProviderImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactResourceImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactServiceImpl.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImplTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/SubscriptionTest.java

Now that we have programmatic model manipulation the Nexus should no longer auto-extend the model. We should also take more care about how and when we query the model

Refactor the ModelNexus

---

prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/snapshot/ResourceSnapshot.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/snapshot/ResourceSnapshotImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactDigitalTwinImpl.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/twin/impl/SensinactTwinTest.java
prototype/northbound/filters/ldap/src/test/java/org/eclipse/sensinact/northbound/filters/ldap/LdapParserTest.java
prototype/northbound/sensorthings/filter/src/test/java/org/eclipse/sensinact/northbound/filters/sensorthings/RcUtils.java

The ResourceSnapshot fails with a ClassCastException when we attempt to populate the value for an Action Resource. We should not attempt to do this at all.

ClassCastException occurs when filtering models with actions

---

prototype/northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/query/WrappedAccessMethodCallParametersDTO.java
prototype/northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/query/jackson/ActParametersDeserializer.java
prototype/northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/query/jackson/WrappedAccessMethodCallParametersDeserializer.java
prototype/northbound/query-handler/src/test/java/org/eclipse/sensinact/northbound/query/test/integration/SerializationTest.java
prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/api/IRestNorthbound.java
prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/ResourceAccessTest.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/SecureAccessTest.java

The legacy sensiNact northbound REST provider expected parameters to be encapsulated in a JSON object, not a raw array. This should continue to work.

Ensure compatibility with old style parameter objects in SET/ACT

---

prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/EMFUtil.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/emf/util/EMFUtilTest.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/ResourceAccessTest.java
prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/TestUtils.java

In some cases we saw infinite recursion when converting data. Also the converter is not suitable for some JSON types, so we should attempt to use those where possible.

Avoid errors when converting between data types

---

prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientHandler.java

This avoids to propagate the exception to Paho, which will disconnect on error

Catch and log MQTT message listener exceptions

---

prototype/core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/GET.java
prototype/core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/GetParam.java
prototype/core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/SetParam.java
prototype/core/api/src/main/java/org/eclipse/sensinact/core/command/GetLevel.java
prototype/core/api/src/main/java/org/eclipse/sensinact/core/model/ResourceBuilder.java
prototype/core/api/src/main/java/org/eclipse/sensinact/core/session/ResourceDescription.java
prototype/core/api/src/main/java/org/eclipse/sensinact/core/session/SensiNactSession.java
prototype/core/api/src/main/java/org/eclipse/sensinact/core/twin/SensinactResource.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/ResourcePullHandler.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/ResourcePushHandler.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/impl/ResourceBuilderImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/ModelNexus.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactResourceImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/AbstractResourceMethod.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/ActMethod.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/GetMethod.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/SensinactWhiteboard.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/SetMethod.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/command/impl/WhiteboardImplTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/impl/ModelBuildingTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/SubscriptionTest.java
prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/whiteboard/impl/WhiteboardImplTest.java
prototype/core/models/metadata/src/main/resources/model/metadata.ecore
prototype/core/models/metadata/src/main/resources/model/metadata.genmodel
prototype/distribution/features/timescale-history-provider-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/history/timescale/TimescaleHistoryFeatureIntegrationTest.java
prototype/examples/reflective/src/main/java/org/eclipse/sensinact/prototype/reflective/ProgrammaticModelProvider.java

* Uses `isExternalGet` and `isExternalSet` flags of the `ResourceAttribute` to check if an external handler must be called
* Adds the `externalGetCacheMs` entry in `ResourceAttribute` to define the time to wait before calling again the external Get handler
* The value returned by the handlers is stored in the twin
* Added `GetLevel` to define 3 levels of resource access:
* `WEAK`: always return the twin value, never call the external get
* `NORMAL`: call the external get if no twin value is available or if the `externalGetCacheMs` duration expired
* `STRONG`: always call the external get.
* Doesn't work with resources defined outside the ModelBuilder, like pre-defined admin resources.
Also adds a small fix in the history provider integration tests to protect against a null pointer when …

Implementation of pull-based resources

---

prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SessionManager.java
prototype/northbound/rest/integration-test.bndrun
prototype/northbound/sensorthings/rest.gateway/integration-test.bndrun
prototype/northbound/websocket/integration-test.bndrun
prototype/northbound/websocket/pom.xml
prototype/northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketCreator.java
prototype/northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketEndpoint.java
prototype/northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketJettyRegistrar.java
prototype/northbound/websocket/src/test/java/org/eclipse/sensinact/northbound/websocket/integration/SecureWebSocketTest.java
prototype/northbound/websocket/src/test/java/org/eclipse/sensinact/northbound/websocket/integration/WebSocketTest.java
prototype/pom.xml

This commit makes several improvements to the northbound websocket interface:
* Authentication using the sensinact Authenticator services
* Improved ordering guarantees. Websocket clients will always receive a subscription response before receiving their first notification for that subscription
* Thread safety - the web socket session was not updated in a thread safe way so notifications would sometimes fail with NPE

Northbound websocket improvements

---

northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/api/AbstractResultDTO.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/result/ResponseSetDTO.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/result/TypedResponse.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/result/jackson/TypedResponseDeserializer.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/impl/QueryHandler.java
northbound/query-handler/src/test/java/org/eclipse/sensinact/northbound/query/test/integration/SerializationTest.java

In some cases, the JSON result sent by sensiNact had two "type" keys at root level.
This PR fixes the Jackson serialization annotations and adds a test to avoid reproducing the error.

Fix cases where a northbound result had 2 'type' keys

---

core/api/src/main/java/org/eclipse/sensinact/core/push/dto/GenericDto.java
core/impl/src/main/java/org/eclipse/sensinact/prototype/extract/impl/GenericDtoDataExtractor.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/dto/DeviceMappingOptionsDTO.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
southbound/device-factory/device-factory-core/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/RecordHandlingTest.java

This option allows to choose if updates with a null value are accepted or ignored (previous and now default behaviour).
The device factory core has also been updated to accept a "null.action" entry in its mapping options.
It accepts null values by default.

Add NullAction field to GenericDTO

---

northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/DatastreamMapper.java
northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/DatastreamsMapper.java
northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ObservedPropertiesMapper.java
northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/SensorsMapper.java
northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ThingsMapper.java
northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/ObservationHistoryTest.java

* Use a single Timescale container to test the REST gateway (requires #225). That speeds up tests and handles the table presence issues
* Wait for the REST API to be up & running before running tests
* MQTT: avoid getting providers/resources snapshots when notified of their deletion

Updates for SensorThings 

---

.licenserc.yaml
.readthedocs.yaml

This file is used by ReadTheDocs to configure the build, as it's not possible in the RTD project anymore.
The RTD build trigger (WebHook or CI action) is not set up yet, an issue has been created on Eclipse HelpDesk for that.

Added configuration files for ReadTheDocs builds

---

southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientConfiguration.java
southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientHandler.java
southbound/mqtt/mqtt-client/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/test/MqttAuthTest.java

The password field is always null if of type char[]. It is loaded correctly as a String.

Use String instead of char[] for password configuration

---

northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/SensorthingsMqttNorthbound.java

Integration tests were failing because sensiNact notifications and their handling were done in (at least) 2 threads, meaning that the order of sending of notification couldn't be guaranteed.
This commit uses a single thread that handles the publication of messages in the same order as the notifications, still using multiple threads to handle notifications and payload generation.
This should fix the CI test failures of the SensorThings MQTT project

SensorThings MQTT: Queue notifications to keep their order

---

distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManagerTest.java
distribution/launcher/src/test/resources/configs/invalid/configuration-null.json
docs/source/distribution/Launcher.md

This PR filters out invalid configuration values before letting the Configurator load them.
See #304 for more details

Fix for null values handling in configuration

---

.github/workflows/ci-build.yml
core/impl/integration-test.bndrun
northbound/filters/ldap/integration-test.bndrun
northbound/query-handler/integration-test.bndrun
northbound/rest/integration-test.bndrun
northbound/security/openid-connect/integration-test.bndrun
northbound/sensorthings/mqtt/integration-test.bndrun
northbound/sensorthings/rest.gateway/integration-test.bndrun
northbound/websocket/integration-test.bndrun
pom.xml
southbound/history/timescale-provider/integration-test.bndrun
southbound/history/timescale-provider/tests.bnd
southbound/http/http-device-factory/integration-test.bndrun
southbound/mqtt/mqtt-device-factory/integration-test.bndrun
southbound/virtual/virtual-temperature-sensor/integration-test.bndrun

Fixes #301
Introduces build profiles for sensiNact to enforce consistent bndrun resolutions in CI and a profile for rapid turnaround of dependabot updates
Note that the first commit is expected to fail the build because the bndruns aren't yet updated.

Update build plugin configuration to improve bndrun management

---

core/impl/integration-test.bndrun
core/impl/pom.xml
distribution/features/core-feature/pom.xml
distribution/features/core-feature/src/main/resources/core-feature.json
distribution/features/core-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/core/CoreFeatureTest.java
distribution/launcher/export.bndrun
northbound/filters/ldap/integration-test.bndrun
northbound/query-handler/integration-test.bndrun
northbound/rest/integration-test.bndrun
northbound/security/openid-connect/integration-test.bndrun
northbound/sensorthings/mqtt/integration-test.bndrun
northbound/sensorthings/rest.gateway/integration-test.bndrun
northbound/websocket/integration-test.bndrun
pom.xml
southbound/history/timescale-provider/integration-test.bndrun
southbound/http/http-callback-whiteboard/integration-test.bndrun
southbound/http/http-device-factory/integration-test.bndrun
southbound/mqtt/mqtt-device-factory/integration-test.bndrun
southbound/virtual/virtual-temperature-sensor/integration-test.bndrun

Updating to a more recent version of slf4j, as the current version is an older version.

Bump slf4j to v2.0.11 (Issue #328)

---

core/api/src/main/java/org/eclipse/sensinact/core/push/DataMappingException.java
core/api/src/main/java/org/eclipse/sensinact/core/push/DataUpdate.java
core/api/src/main/java/org/eclipse/sensinact/core/push/DataUpdateException.java
core/api/src/main/java/org/eclipse/sensinact/core/push/FailedUpdatesException.java
core/impl/integration-test.bndrun
core/impl/src/main/java/org/eclipse/sensinact/core/dto/impl/AbstractUpdateDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/dto/impl/FailedMappingDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/GenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/DataUpdateImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetMetadataCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/AnnotationBasedDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/GenericDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/DataUpdateServiceTest.java

This commit defines the exceptions that will be used to fail pushed updates, including bulk updates, and will be used to fail the returned promise. These exceptions return the error, and the original DTO so that users can attempt to work out what they did wrong.
Fixes #340

Better error handling for pushed updates

---

docs/source/southbound/device-factory/core.md
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/LocaleUtils.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/RecordPath.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/ValueType.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/dto/DeviceMappingOptionsDTO.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/ResourceMappingHandler.java
southbound/device-factory/device-factory-core/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/ValueTypeTest.java
southbound/device-factory/device-factory-core/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/RecordHandlingTest.java
southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/HttpDeviceFactory.java
southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/HttpDeviceFactoryTest.java

This PR enhance the usability of the Device Factory:
* Added support for other primitive types: bytes, char, short and boolean
* Parsed arrays (`byte[]`) are now stored as immutable lists
* Enhanced date time parsing options (added support for locale-based long string, documentation was updated)
* Added a `log.errors` flag to the mapping options to ease debugging by tracing parsing, mapping and digital twin update errors
* The HTTP device factory now logs exceptions encountered, as some SSL connection errors were just indicating "status code 0" with no other details.

Device factory updates

---

core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/emf/compare/EMFCompareUtil.java

Changes from services in dynamic providers (services map) were ignored.

Fix change notification for services in dynamic provider

---

core/api/src/main/java/org/eclipse/sensinact/core/notification/LifecycleNotification.java
core/api/src/main/java/org/eclipse/sensinact/core/notification/ResourceActionNotification.java
core/api/src/main/java/org/eclipse/sensinact/core/notification/ResourceDataNotification.java
core/api/src/main/java/org/eclipse/sensinact/core/notification/ResourceMetaDataNotification.java
core/impl/src/test/java/org/eclipse/sensinact/core/notification/impl/NotificationSenderTest.java
northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java
northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/notification/ResourceNotificationsTest.java
northbound/session/session-impl/src/test/java/org/eclipse/sensinact/nortbound/session/integration/SessionSubscribeTest.java
northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketEndpoint.java
southbound/virtual/virtual-temperature-sensor/src/main/java/org/eclipse/sensinact/gateway/southbound/virtual/temperature/VirtualTemperatureDto.java

Filtering at the model level is extremely useful as it permits efficient tracking of multiple providers using the same model. The model URI is required to ensure strict uniqueness, however the model uri is difficult to represent in topic syntax, and would need large amounts of escaping. The trade off is therefore to allow the model name to be used in the topic for rapid checking, with the filter being available for more precise matching if needed.

Include the model name in topic notifications

---

core/impl/src/test/java/org/eclipse/sensinact/core/integration/EMFUpdateServiceTest.java
core/models/provider/src/main/resources/model/sensinact.ecore
core/models/provider/src/main/resources/model/sensinact.genmodel

A custom admin service with resources don't work as the admin service eClass is resolved by the eReferenceType and ends  up with the default Admin eClass.

use real eClass from service not from reference

---

core/impl/src/main/java/org/eclipse/sensinact/core/model/impl/ModelImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/impl/SensinactModelManagerImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/impl/ModelBuildingTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/nexus/impl/NexusTest.java

The model manager API provides a deletion method, but this was not implemented. This commit implements deletion logic, which delegates to the Model Nexus. The Model Nexus:
1. Finds the Model
2. If found it deletes any and all providers using the model, then it deletes the model from its owning EPackage
3. If the EPackage is now empty of models then the EPackage is removed from the Model Nexus
The ModelImpl has also been updated to check the the model is still registered before allowing any action. This prevents deleted models from being used after they are deleted.

Implement model deletion in the Model Manager

---

core/api/src/main/java/org/eclipse/sensinact/core/twin/SensinactDigitalTwin.java

The method getProviders(String, String) existed in the EMF Twin, but not the base twin. As we already use the model package uri extensively in that interface we should expose it here as well.

Expose #getProviders(String modelPackageUri, String model) from the twin

---

core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/NullAction.java
core/impl/src/main/java/org/eclipse/sensinact/core/dto/impl/AbstractUpdateDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/EMFGenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/GenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/SensinactWhiteboard.java
core/impl/src/test/java/org/eclipse/sensinact/core/command/impl/WhiteboardImplTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/CustomBaseValueDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/GenericDtoExtractorTest.java

In some cases null is a valid value to return, but should not be used to initialize a resource. For example if a DTO contains some optional resources which may never be set for some providers, but will be set for others, and those resources may be null, then this was not previously possible

Add support for nullable data which should not create a resource

---

core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/DataUpdateServiceTest.java

The UPDATE_IF_PRESENT logic would always run even if the data value was not null. This has been fixed and regression tests added for all NullAction behaviours.

Fix missing check in SetValueCommand

---

core/api/src/main/java/org/eclipse/sensinact/core/push/dto/GenericDto.java
core/emf-api/src/main/java/org/eclipse/sensinact/core/emf/dto/EMFGenericDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/EMFGenericDtoDataExtractor.java

The EMF dto altered the GenericDto so that it could extend it. The GenericDto was intentionally final to prevent usage mistakes in the API. There are few fields and we should copy them.

Reinstate final modifier for GenericDto

---

northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketEndpoint.java

`prepareFilter()` can return null if the query filter string wasn't blank but the filter does nothing (empty filter in LDAP, ...).
This PR avoids an Exception to be thrown as `Predicate.and()` fails when the given predicate is null.

Added tests for null parsed filter when creating a predicate

---

core/impl/src/main/java/org/eclipse/sensinact/core/metrics/impl/CallbackReporter.java
core/impl/src/main/java/org/eclipse/sensinact/core/metrics/impl/MetricsManager.java
core/impl/src/main/java/org/eclipse/sensinact/core/metrics/impl/MetricsProviderHandler.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/metrics/MetricsTest.java

* If the `provider.enabled` option of `sensinact.metrics` is true, the metrics bulk DTO is pushed to the gateway.
* Added a test to ensure the provider exists
* Fixed the JVM gauge sometimes not being registered

Added metrics provider

---

core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/AbstractDescriptiveAct.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/AbstractDescriptiveReadOnly.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/AbstractDescriptiveReadWrite.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardAct.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardActDescription.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardConstants.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardGet.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardHandler.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardResourceDescription.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/WhiteboardSet.java
core/api/src/main/java/org/eclipse/sensinact/core/whiteboard/package-info.java
core/impl/src/main/java/org/eclipse/sensinact/core/command/impl/GatewayThreadImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/AbstractResourceMethod.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/ActMethod.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/GetMethod.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/RegistryKey.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/SensinactWhiteboard.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/SetMethod.java
core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/WhiteboardContext.java
core/impl/src/test/java/org/eclipse/sensinact/core/command/impl/WhiteboardImplTest.java

This PR adds support for new resources handling whiteboard services that doesn't rely on method annotations.
This eases the creation of resources and handlers on-the-go.
The existing whiteboard API with annotated methods hasn't been modified.

Extend whiteboard capabilities

---

southbound/mqtt/mqtt-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/factory/MqttDeviceFactoryHandler.java
southbound/mqtt/mqtt-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/factory/ContextTest.java

The MQTT device factory adds topic segments to the mapping context, e.g. `foo/bar` gives `context.topic-0` set to `foo`.
This was failing if the the topic was starting with a `/`, e.g. `/foo/bar`.
This PR fixes the segmentation process, following the MQTT specification:
* `/foo`, `foo` and `foo/` are different
* with a `/` prefix, `context.topic-0` is always an empty string
* with a `/` suffix, `context.topic-last` is always an empty string
* `foo/bar` and `foo//bar` are equivalent, but `foo/bar` and `foo/ /bar` are different (and `context.topic-1` will be a space character)

Fixed computation of topic segments for MQTT DevFactory context

---

core/api/src/main/java/org/eclipse/sensinact/core/model/Resource.java
core/api/src/main/java/org/eclipse/sensinact/core/model/ResourceBuilder.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ResourceSnapshotImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/impl/ResourceBuilderImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/impl/ResourceImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/impl/ModelBuildingTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/twin/impl/SensinactTwinTest.java
core/models/metadata/src/main/resources/model/metadata.ecore
core/models/metadata/src/main/resources/model/metadata.genmodel

Provider instances have the ability to independently set metadata values, however in most cases metadata is common to all instances of a model and it is relatively static. It therefore makes sense to be able to define default metadata at the resource model level which is applied to the instance when it is first created.
Note that only the Extra metadata is used to populate the defaults. This prevents other data about the resource (e.g. the resource type and value type) from being added and bloating the metadata. To differentiate default metadata values from metadata values which are set later the default metadata values will have no associated timestamp. This is in line with the behaviour for default resource values.

Allow default resource metadata to be set in the model

---

northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/query/QueryGetDTO.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/dto/result/ResponseGetDTO.java
northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/impl/QueryHandler.java
northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/api/IRestNorthbound.java
northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java

Query handler QueryGetDTO now has an `includeMetadata` field, false by default, to include metadata with the resource value.
Metadata are provided like in the resource description, as a list in an `attributes` entry.
The `attributes` entry is null and doesn't appear in JSON serizalization if the metadata weren't requested.
Follows #431

Added option to include metadata when getting resource value

---

core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Data.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/DuplicateAction.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Metadata.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Provider.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Resource.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Service.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Timestamp.java
core/api/src/main/java/org/eclipse/sensinact/core/push/dto/GenericDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/dto/impl/AbstractUpdateDto.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/GenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetMetadataCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/AnnotationBasedDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/CustomBaseValueDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/GenericDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/DataUpdateServiceTest.java

This commit adds a DuplicateAction to the pushed updates, which determines the behaviour when the pushed update contains a duplicate value or metadata value. A duplicate value is determined by object equality, or == if one value is null. The default for resource values is that duplicates updates are applied, updating the timestamp and generating a update event. The default for metadata values is that duplicate updates are ignored, avoiding timestamp updates and update events. The reason for this difference is that repeated data readings can often give the same value, but this is a new reading. In general metadata values do not change, and so duplicates aren't interesting.

Allow data and metadata update de-duplication

---

docs/source/southbound/history/timescale.md
southbound/history/timescale-provider/src/main/java/org/eclipse/sensinact/gateway/southbound/history/timescale/TimescaleHistoricalStore.java

Errors (e.g. misconfiguration) during startup were only logged in the debug and were therefore not visible.

Fix logging of errors

---

northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DtoMapper.java

The getValue method of te ResourceSnapshot can return null, so we should handle it.

Null check to avoid NPE

---

pom.xml

Compiling project with Maven version lower to 3.8.1 fails and stop on error 
`
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-maven-plugin:7.0.0:bnd-process (default) on project annotation: The plugin biz.aQute.bnd:bnd-maven-plugin:7.0.0 requires Maven version 3.8.1 -> [Help 1]`
=> Maven should specify the minimum version to 3.8.1 to stop on compile's precondition check

specify Maven minimum version

---

core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java

When a custom DTO is not defined correctly, the DataUpdate should return a failed promise with a DataMappingException.
The DataMappingException requires the originalDto to be non null, which wasn't the case in the fixed snippet.

Fixed failure result creation due to missing originalDto field

---

core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ProviderSnapshotImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/twin/impl/SensinactDigitalTwinImpl.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/filter/FilterTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/twin/impl/SensinactTwinTest.java

Filtering should only add services and resources which pass the filters. Services with no resources should be excluded, as should providers with no services. This commit ensures the minimal snapshot is created and returned.
Fixes #517

Ensure filtering properly removes services and resources

---

core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/EMFGenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/GenericDtoDataExtractor.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetMetadataCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/notification/impl/NotificationAccumulatorImpl.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/GenericDtoExtractorTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/DataUpdateServiceTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/notification/impl/NotificationSenderTest.java

Try to write data values first, but ensure to update the data notification's metadata if metadata changes later.
Fixes #519

Ensure that metadata set commands pass successfully

---

core/api/src/main/java/org/eclipse/sensinact/core/command/AbstractSensinactCommand.java
core/api/src/main/java/org/eclipse/sensinact/core/command/DependentCommand.java
core/api/src/main/java/org/eclipse/sensinact/core/command/GatewayThread.java
core/emf-api/src/main/java/org/eclipse/sensinact/core/emf/command/AbstractSensinactEMFCommand.java
core/impl/src/main/java/org/eclipse/sensinact/core/command/impl/GatewayThreadImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/emf/compare/EMFCompareUtil.java
core/impl/src/main/java/org/eclipse/sensinact/core/notification/impl/AbstractNotificationAccumulatorImpl.java
core/impl/src/main/java/org/eclipse/sensinact/core/notification/impl/ImmediateNotificationAccumulator.java
core/impl/src/main/java/org/eclipse/sensinact/core/notification/impl/NotificationAccumulator.java
core/impl/src/main/java/org/eclipse/sensinact/core/notification/impl/NotificationAccumulatorImpl.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/impl/ModelBuildingTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/nexus/impl/NexusTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/model/nexus/impl/SubscriptionTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/notification/impl/NotificationSenderTest.java
core/impl/src/test/java/org/eclipse/sensinact/core/twin/impl/SensinactTwinTest.java

It seems there is no interest into having the NotificationAccumulator as public API, as discussed in #496 
This PR proposes the changes required to move NotificationAccumulator into the core.impl bundle

Make NotificationAccumulator private

---

core/api/pom.xml
core/api/src/main/java/org/eclipse/sensinact/core/twin/DefaultTimedValue.java
core/api/src/main/java/org/eclipse/sensinact/core/twin/TimedValue.java
core/api/src/test/java/org/eclipse/sensinact/core/twin/DefaultTimedValueTest.java

We must mark the extra constructors as ignored, and also the isEmpty property which is not part of the data. Tests added to ensure compatability going forward

Ensure proper JSON serialization of the default timed value implementation

---

southbound/wot/api/src/main/java/org/eclipse/sensinact/gateway/southbound/wot/api/Namespaces.java
southbound/wot/api/src/test/java/org/eclipse/sensinact/gateway/southbound/wot/test/ParserTest.java
southbound/wot/api/src/test/resources/data/context.jsonld

According to the specification, `@Context` can be:
- a URI
- a Map (prefix -> URI)
- an array mixing URIs and maps

Added support for complex contexts in WoT Thing Description

---

core/impl/integration-test.bndrun
filters/ldap/integration-test.bndrun
filters/resource.selector.impl/integration-test.bndrun
northbound/query-handler/integration-test.bndrun
northbound/rest/integration-test.bndrun
northbound/security/openid-connect/integration-test.bndrun
northbound/sensorthings/mqtt/integration-test.bndrun
northbound/sensorthings/rest.gateway/integration-test.bndrun
northbound/session/session-impl/integration-test.bndrun
northbound/websocket/integration-test.bndrun
pom.xml
southbound/history/timescale-provider/integration-test.bndrun
southbound/http/http-callback-whiteboard/integration-test.bndrun
southbound/http/http-device-factory/integration-test.bndrun
southbound/mqtt/mqtt-device-factory/integration-test.bndrun
southbound/rules/easy-rules/config/integration-test.bndrun
southbound/rules/easy-rules/osgi/integration-test.bndrun
southbound/rules/rules.impl/integration-test.bndrun
southbound/virtual/virtual-temperature-sensor/integration-test.bndrun
southbound/wot/core/integration-test.bndrun
southbound/wot/http/integration-test.bndrun

The Aries Typed Events 1.0.0 release contains some useful bug fixes and also support for:
* Record types as events
* Single level wildcards (enable in config)

Update to Aries Typed Event 1.0.0

---

core/impl/integration-test.bndrun
filters/ldap/integration-test.bndrun
filters/resource.selector.impl/integration-test.bndrun
northbound/query-handler/integration-test.bndrun
northbound/rest/integration-test.bndrun
northbound/sensorthings/mqtt/integration-test.bndrun
northbound/sensorthings/rest.gateway/integration-test.bndrun
northbound/session/session-impl/integration-test.bndrun
northbound/websocket/integration-test.bndrun
pom.xml
southbound/history/timescale-provider/integration-test.bndrun
southbound/http/http-device-factory/integration-test.bndrun
southbound/mqtt/mqtt-device-factory/integration-test.bndrun
southbound/rules/easy-rules/config/integration-test.bndrun
southbound/rules/easy-rules/osgi/integration-test.bndrun
southbound/rules/rules.impl/integration-test.bndrun
southbound/virtual/virtual-temperature-sensor/integration-test.bndrun
southbound/wot/core/integration-test.bndrun
southbound/wot/http/integration-test.bndrun

This update will stop the repeated stack traces polluting the sensiNact log files

Update to Aries Typed Events 1.0.1

---

core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Data.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Metadata.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Model.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/ModelPackageUri.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Provider.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Resource.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Service.java
core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/dto/Timestamp.java
core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/AnnotationBasedDtoExtractorTest.java

This commit enhances the AnnotationMapping utility to scan Java Records as well as DTO types. This offers consistent handling whichever mechanism the user chooses to use.
Fixes #515

Support pushed updates using Java Records

---

distribution/features/timescale-history-provider-feature/pom.xml
northbound/sensorthings/rest.gateway/integration-test.bndrun
northbound/sensorthings/rest.gateway/pom.xml
northbound/sensorthings/rest.gateway/tests.bnd
pom.xml
southbound/history/timescale-provider/integration-test.bndrun
southbound/history/timescale-provider/pom.xml
southbound/history/timescale-provider/tests.bnd

This commit updates to the latest release of testcontainers, and centralises the dependency in parent. This is necessary as the dependency is used in multiple parts of the gateway build, such as northbound, southbound and distribution

Update to testcontainers 1.21 and move dependency to parent

---

northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/Datastream.java
northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/Observation.java
northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/TimeInterval.java
northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/jackson/TimeIntervalDeserializer.java
northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/jackson/TimeIntervalSerializer.java

This commit fixes two issues with the sensorthings DTOs
* The DataStream and Observation types used Instant to represent fields that are, in fact, time intervals. As Java has no built in type for this the commit adds TimeInterval, including a Jackson parser for the formats permitted by ISO 8601 (start and end, start and duration, duration and end)
* The Datastream observedArea has been loosened to permit any GeoJSON Geometry. This is to fit with the observed behaviour of FROST server (the reference implementation) which does not enforce that the observed area is a Polygon (unlike the specification text)

Sensorthings specification alignments

---

core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/AnnotationBasedDtoExtractorTest.java

Metadata updates are permitted to use null values to indicate that a metadata value should be removed. The annotation mapper must be able to handle this

Avoid NPE when metadata has null values

---

core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/emf/EMFUtil.java
core/impl/src/test/java/org/eclipse/sensinact/core/emf/util/EMFUtilTest.java
core/models/testdata/src/main/resources/model/testdata.ecore
core/models/testdata/src/main/resources/model/testdata.genmodel

Just bring back the functionality to get an alternative model name from an EAnnotation.

Revert/fix getModelName from annotation

---

DEPENDENCIES
core/impl/integration-test.bndrun
core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
core/impl/src/test/java/org/eclipse/sensinact/core/integration/EMFUpdateServiceTest.java
northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/ResourceAccessTest.java

Currently, the listeners are notified of a resource update with the value provided by the updater.
Instead, they should be notified with the converted value, when appliable.
The solves a class cast exception in org.eclipse.sensinact.core.snapshot.ResourceDataFilter (in the ICriterion file), as it expects admin/location to be a GeoJsonObject while being notified with a map.
Also fixed an integration test failing on Windows due to timestamp precision

Notifications should contain the data really stored in model

---

northbound/query-handler-impl/src/main/java/org/eclipse/sensinact/northbound/query/impl/QueryHandler.java

Check if TimedValue.getTimestamp() is not null before calling toEpocMillis().
The timestamp can be null when the resource is managed via the EMF API but no timestamp has explicitly been set.
As the result is a `long`, we might want to set it to 0.

Protect snapshot from null timestamp in query handler
