- platform/sensinact-security/sensinact-security-core/src/test/java/org/eclipse/sensinact/gateway/core/security/test/TestUserManager.java
Remove unnecessary configuration from UserManager tests
> Futher test improvements

- distribution/pom.xml
- distribution/sdk/pom.xml
Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>
> Added SDK BOM

- prototype/examples/model-based/src/main/java/org/eclipse/sensinact/prototype/resource/ResourceModelProvider.java
- prototype/examples/reflective/src/main/java/org/eclipse/sensinact/prototype/reflective/ProgrammaticModelProvider.java
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
> prevent sonar security message

- .github/workflows/format.yml
> Add Editor Config format validation

- .github/workflows/format.yml
> Get the editor config validation working properly

- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImplTest.java
remove unused `@Mock Resource resource;`
> Simplify with @InjectMocks, @ParameterizedTest, descriptive fields

- .licenserc.yaml
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
> Update .licenserc.yaml - ignore json

- .licenserc.yaml
this changes only the default content. NOT the pattern that tests against the header
> Update .licenserc.yaml - Content of default header

- .github/workflows/ci-build.yml
- .github/workflows/stale.yml
CI build and stale issue management
> Further PR checking improvements

- .github/workflows/eclipse_ip.yml
- prototype/pom.xml
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
> move license check into profile

- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/EventTopicNames.java
replace not allowed . separators with /
Signed-off-by: Guido Grune <g.grune@datainmotion.com>
> fix topic names replace . with /

- .github/workflows/eclipse_ip.yml
- prototype/northbound/rest/pom.xml
Signed-off-by: Stefan Bischof <stbischof@bipolis.org>
> use org.osgi.service.jakartars:2.0.0-RC1

- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/ResourceShortDescription.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/SensiNactSession.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactModel.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/TimedValue.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactModelImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactProviderImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactServiceImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/TimedValueImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SessionManager.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusImpl.java
- prototype/docs/DataAccess.md
- prototype/docs/DataModel.md
* Implementation of the methods that will be required by the REST northbound endpoint
* Small fix on the provider existence check
* Resources of the Admin service of new providers now have a timestamp
> Preparation of sensiNact core for northbound endpoints

- prototype/northbound/rest/pom.xml
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/api/IRestNorthbound.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/ObjectMapperProvider.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestAccessApplication.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/SensinactSessionProvider.java
* Provides the same REST API as the previous sensiNact REST northbound for DESCRIBE, GET and SET.
* Lacks ACT and (UN)SUBSCRIBE
* Shortcut URLs were removed
> REST Northbound implementation (GET/SET)

- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
Fixed the removal of notification listeners
> Fixed notification listeners removal

- .github/workflows/eclipse_ip.yml
- prototype/distribution/features/core-feature/pom.xml
- prototype/distribution/features/jakarta-rest-whiteboard-feature/pom.xml
- prototype/distribution/features/pom.xml
- prototype/distribution/launcher/export.bndrun
- prototype/distribution/launcher/pom.xml
- prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
- prototype/pom.xml
* Prototype creating features that can be launched
* Add support for configuration management
> Prepare for a launchable gateway

- prototype/northbound/rest/integration-test.bndrun
- prototype/northbound/rest/pom.xml
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/api/IRestNorthbound.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/dto/notification/ResourceDataNotificationDTO.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/dto/notification/ResourceLifecycleNotificationDTO.java
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestNorthbound.java
- prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/notification/ResourceNotificationsTest.java
Implementation + test for a Server-Sent Events based resource events subscription (lifecycle and data changes)
> SSE-based SUBSCRIBE for REST northbound

- prototype/distribution/launcher/export.bndrun
- prototype/distribution/launcher/pom.xml
- prototype/distribution/launcher/src/it/resources/config/configuration.json
- prototype/distribution/launcher/src/it/resources/features/test-feature.json
- prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
- prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/FeatureLauncher.java
- prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/integration/FeatureLaunchingIntegrationTest.java
- prototype/distribution/pom.xml
- prototype/pom.xml
> Add integration tests for the feature launcher

- prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/FeatureLauncher.java
> Add logging to the feature launcher

- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactModelImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactResourceImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelTransaction.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ProviderTypeWrapper.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/EMFUtil.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/SensinactCopier.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/SubscriptionTest.java
Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>
> Renamed Nexus and reorganised the classes

- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/LocationsAccess.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/ObservedPropertiesAccess.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/SensorsAccess.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/ThingsAccess.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DatastreamsAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DtoMapper.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/FeaturesOfInterestAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ObservedPropertiesAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/SensorsAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ThingsAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/LinksTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/TestUtils.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/ValueTest.java
* All links are now working
* Value update behaviour is now tested
> More tests for the SensorThings northbound provider

- prototype/core/impl/integration-test.bndrun
- prototype/distribution/features/jakarta-rest-whiteboard-feature/pom.xml
- prototype/distribution/features/jakarta-rest-whiteboard-feature/src/it/resources/config/configuration.json
- prototype/distribution/features/jakarta-rest-whiteboard-feature/src/main/resources/jakarta-rest-whiteboard-feature.json
- prototype/distribution/features/jakarta-rest-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartarest/RestWhiteboardIntegrationTest.java
- prototype/distribution/features/jakarta-rest-whiteboard-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/jakartarest/resource/Resource.java
- prototype/distribution/features/pom.xml
- prototype/distribution/launcher/export.bndrun
- prototype/pom.xml
> Add a Jakarta REST whitboard feature based on Servlet Whiteboard

- prototype/northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/TestUtils.java
- prototype/northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/Datastream.java
- prototype/northbound/sensorthings/dto/src/main/java/org/eclipse/sensinact/sensorthings/sensing/dto/UnitOfMeasurement.java
- prototype/northbound/sensorthings/dto/src/test/java/org/eclipse/sensinact/sensorthings/sensing/dto/JsonMappingTest.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/CountFilter.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/FilterFilter.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/ObjectMapperProvider.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/OrderByFilter.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/SkipFilter.java
- prototype/northbound/sensorthings/rest.api/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/filters/TopFilter.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/DtoMapper.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/FeaturesOfInterestAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/ThingsAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/FiltersTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/LinksTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/TestUtils.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/ValueTest.java
* UnitOfMeasurement is now a DTO instead of a simple Map
* FeatureOfInterest ID doesn't contain a timestamp anymore
* Timestamps are now serizalized as an ISO 8601 string
* Reversed the order of execution of the order, skip, top filters
Note that the tests are a bit slow.
> More tests on SensorThings

- prototype/southbound/device-factory/device-factory-core/pom.xml
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/DeviceFactoryException.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/IDeviceMappingHandler.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/IDeviceMappingParser.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/IDeviceMappingRecord.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/InvalidResourcePathException.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/MissingParserException.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/ParserException.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/RecordPath.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/ResourceMapping.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/VariableNotFoundException.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/VariableSolver.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/dto/DeviceMappingConfigurationDTO.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/dto/DeviceMappingOptionsDTO.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/dto/package-info.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/package-info.java
- prototype/southbound/device-factory/pom.xml
- prototype/southbound/pom.xml
First part of the device factory core
> Added API and utility classes for the device factory

- prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManagerTest.java
The `ENTRY_MODIFY` event can be triggered multiple times, depending on the operating system.
This fix checks if the configuration update is done at least once.
> Fix for the configuration manager test

- .github/workflows/ci-build.yml
- .github/workflows/eclipse_ip.yml
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelTransaction.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ProviderTypeWrapper.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/emf/EMFUtil.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/SubscriptionTest.java
- prototype/core/models/pom.xml
- prototype/core/models/src/main/resources/model/sensinact.ecore
- prototype/core/models/src/main/resources/model/sensinact.genmodel
- prototype/pom.xml
I have realized that a change sneaked in here that will be part of another upcoming PR (the addEPackage References). If it is okay, we can leave it in here, as it does not do anything right now and I would base my changes on there commits anyway. 
Besides that: I added the Method to add and remove links of providers. Providers that are not known, will be created. For unlinking of unkown providers, will right now produce an IllegalArgumentException. I currently have no Strong feelings how we should handle the attempt to unlink something that does not exist. I'm furthermore open on how much Metdata we want to track for each link and in what way we want to publish such changes.
Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>
> Adds linked Providers

- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/IDeviceMappingHandler.java
- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
Implements the device factory handler.
Requires #81 to be merged to work.
> Implementation of the device factory handler

- prototype/pom.xml
- prototype/southbound/mqtt/mqtt-client/pom.xml
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/api/IMqttMessage.java
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/api/IMqttMessageListener.java
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/api/package-info.java
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientConfiguration.java
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientHandler.java
- prototype/southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/SensiNactMqttMessage.java
- prototype/southbound/mqtt/mqtt-client/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/test/MqttTest.java
- prototype/southbound/mqtt/pom.xml
A simple MQTT listener that notifies listeners when a message is received on matching topic(s)
> Initial version of the MQTT southbound provider

- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactModel.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactModelImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ProviderTypeWrapper.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
> Allow querying of providers without knowing the model

- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/integration/session/AdminServiceTest.java
- prototype/southbound/http/http-device-factory/pom.xml
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/HttpDeviceFactory.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/ParsedHttpPeriodicTask.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/ParsedHttpTask.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/SharedHttpClientResources.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/config/HttpDeviceFactoryConfiguration.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/config/HttpDeviceFactoryConfigurationPeriodicDTO.java
- prototype/southbound/http/http-device-factory/src/main/java/org/eclipse/sensinact/gateway/southbound/http/factory/config/HttpDeviceFactoryConfigurationTaskDTO.java
- prototype/southbound/http/pom.xml
Based on Jetty 11 clients using shared resources.
Supports custom headers, Basic Auth, SSL client auth and SSL server certificate verification with custom trust store.
Sends the HTTP response to the device factory handler.
> HTTP device factory implementation

- prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/HttpDeviceFactoryAuthTest.java
- prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/HttpDeviceFactorySSLTest.java
- prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/HttpDeviceFactoryTest.java
- prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/KeyToolUtils.java
- prototype/southbound/http/http-device-factory/src/test/java/org/eclipse/sensinact/gateway/southbound/http/factory/integration/RequestHandler.java
Addition of SSL tests for the HTTP(S) device factory
> HTTP device factory SSL tests

- prototype/southbound/virtual/virtual-temperature-sensor/src/main/java/org/eclipse/sensinact/gateway/southbound/virtual/temperature/VirtualTemperatureSensor.java
- prototype/southbound/virtual/virtual-temperature-sensor/src/main/java/org/eclipse/sensinact/gateway/southbound/virtual/temperature/VirtualTemperatureSensorComponent.java
- prototype/southbound/virtual/virtual-temperature-sensor/src/test/java/org/eclipse/sensinact/gateway/southbound/virtual/temperature/integration/TemperatureSensorTest.java
> Allow multiple virtual temperature sensors from a single config

- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactModel.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactProvider.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactResource.java
- prototype/core/api/src/main/java/org/eclipse/sensinact/prototype/command/SensinactService.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/AbstractInternalSensinactCommand.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactModelImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactProviderImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactResourceImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/command/impl/SensinactServiceImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SensiNactSessionImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SetValueCommand.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/impl/ModelNexus.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/command/impl/GatewayThreadImplTest.java
- prototype/core/impl/src/test/java/org/eclipse/sensinact/prototype/integration/session/AdminServiceTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/AbstractIntegrationTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/FiltersTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/LinksTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/ValueTest.java
* Separate model building from the digital twin
* Do not allow model mutation from the base commands
> Command tidy up

- prototype/distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/FeatureLauncher.java
- prototype/distribution/launcher/src/test/java/org/eclipse/sensinact/gateway/launcher/FeatureLaunchingTest.java
Adds supports for paths like `~/.m2/repository`  or `${M3_REPO}` in the `repository` and `features` configuration entries of the Feature Launcher.
> Allow the use for ~ and environment variables in feature launcher configuration

- prototype/southbound/history/timescale-provider/src/test/java/org/eclipse/sensinact/gateway/southbound/history/timescale/integration/TimescaleHistoryTest.java
On Windows, `System.getenv().get("PATH")` can return `null`.
As testcontainers auto-selects the way to contact docker, a more stable approach is to try to contact the Docker daemon directly and abort the test suite if that fails.
> Fix docker detection

- prototype/southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/ValueType.java
- prototype/southbound/device-factory/device-factory-core/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/ValueTypeTest.java
Return null for integers in that case
> DeviceFactory: check number values for NaN and Inf

- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/snapshot/ProviderSnapshotImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/snapshot/ResourceSnapshotImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/twin/impl/SensinactDigitalTwinImpl.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/SensinactWhiteboard.java
- prototype/northbound/sensorthings/rest.gateway/src/main/java/org/eclipse/sensinact/sensorthings/sensing/rest/impl/RootResourceAccessImpl.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/ObservationHistoryTest.java
- prototype/southbound/history/timescale-provider/src/main/java/org/eclipse/sensinact/gateway/southbound/history/timescale/TimescaleHistoricalStore.java
Fix some issues present in the provider related to NPEs and using the incorrect provider name
> Fixes for the OGC Sensorthings Northbound provider

- prototype/distribution/features/northbound-rest-feature/src/main/resources/northbound-rest-feature.json
- prototype/distribution/features/pom.xml
- prototype/distribution/features/timescale-history-provider-feature/pom.xml
- prototype/distribution/features/timescale-history-provider-feature/src/it/resources/config/configuration.json
- prototype/distribution/features/timescale-history-provider-feature/src/main/resources/timescale-history-provider-feature.json
- prototype/distribution/features/timescale-history-provider-feature/src/test/java/org/eclipse/sensinact/gateway/feature/integration/history/timescale/TimescaleHistoryFeatureIntegrationTest.java
- prototype/distribution/test-utils/src/main/java/org/eclipse/sensinact/gateway/feature/utilities/test/ServerProcessHandler.java
- prototype/northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/impl/QueryHandler.java
- prototype/northbound/rest/integration-test.bndrun
- prototype/northbound/rest/pom.xml
- prototype/northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/ObjectMapperProvider.java
- prototype/northbound/websocket/integration-test.bndrun
- prototype/northbound/websocket/pom.xml
- prototype/northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/WebSocketEndpoint.java
* Include NPE fixes for describing Action resources
* Include an ObjectMapper configured to serialize Instant to a String timestamp
> Add a feature for the timescale history provider

- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/impl/SetMetadataCommand.java
- prototype/core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/ModelNexus.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/PropertyMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/SensorthingsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/DatastreamMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/DatastreamsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/FeaturesOfInterestMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/HistoricalLocationsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/LocationsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ObservationsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ObservedPropertiesMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ObservedPropertyMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/SensorMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/SensorsMapper.java
- prototype/northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/mappers/ThingsMapper.java
- prototype/northbound/sensorthings/mqtt/src/test/java/org/eclipse/sensinact/gateway/northbound/sensorthings/mqtt/integration/InsecureMqttNotificationsTest.java
This commit adds support for three segment topic names in the Sensorthings MQTT support.
> Add remaining support for OGC Sensorthings MQTT

- prototype/.editorconfig
- prototype/docs/southbound/Southbound.md
- prototype/docs/southbound/device-factory/core.md
- prototype/docs/southbound/device-factory/csv.md
- prototype/docs/southbound/device-factory/json.md
- prototype/docs/southbound/device-factory/tuto-parser.md
- prototype/docs/southbound/history/history.md
- prototype/docs/southbound/history/timescale.md
- prototype/docs/southbound/http/http-callback.md
- prototype/docs/southbound/http/http-device-factory.md
- prototype/docs/southbound/mqtt/mqtt-client.md
- prototype/docs/southbound/mqtt/mqtt-device-factory.md
- prototype/southbound/device-factory/parser-csv/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/parser/csv/CsvParser.java
* Description of existing southbound providers
* Tutorial on writing a parser for the device factory
* Small fix in in the device factory CSV parser to support the "\t" configuration
> Add documentation for southbound providers

- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/Coordinates.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/Feature.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/FeatureCollection.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/GeoJsonObject.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/GeometryCollection.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/LineString.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/MultiLineString.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/MultiPoint.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/MultiPolygon.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/Point.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/Polygon.java
- prototype/core/geo-json/src/main/java/org/eclipse/sensinact/gateway/geojson/utils/GeoJsonUtils.java
- prototype/core/geo-json/src/test/java/org/eclipse/sensinact/gateway/geojson/GeoJsonUtilsTest.java
* Adds support for hashCode(), equals() and toString() to GeoJSON types
* Adds a GeoJsonUtils class with static utility methods to create GeoJSON objects
> Added utility methods to GeoJSON

- prototype/northbound/sensorthings/rest.gateway/integration-test.bndrun
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/AbstractIntegrationTest.java
- prototype/northbound/sensorthings/rest.gateway/src/test/java/org/eclipse/sensinact/sensorthings/sensing/rest/integration/TestUtils.java
- prototype/southbound/http/http-callback-whiteboard/pom.xml
- prototype/southbound/http/pom.xml
These commits try to remove warnings and errors in the HTTP tests
> Wait for sensorThings servlet before REST gateway tests

- distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
- distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/FeatureLauncher.java
Don't try to stop fragment bundles
> Protect against NPE and BundleException

- core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/ACT.java
- core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/ActParam.java
- core/annotation/src/main/java/org/eclipse/sensinact/core/annotation/verb/GetParam.java
- core/impl/src/main/java/org/eclipse/sensinact/prototype/whiteboard/impl/AbstractResourceMethod.java
- core/impl/src/test/java/org/eclipse/sensinact/prototype/command/impl/WhiteboardImplTest.java
- docs/core/Core.md
- docs/core/CoreModel.md
- docs/core/data-model/DataModel.md
- docs/core/data-model/EMFModel.md
- docs/northbound/RestDataAccess.md
- docs/northbound/SensorthingsMqttAccess.md
- docs/northbound/SensorthingsRestAccess.md
- docs/northbound/WebsocketDataAccess.md
- docs/southbound/Southbound.md
- docs/southbound/custom/custom.md
- northbound/query-handler/src/test/java/org/eclipse/sensinact/northbound/query/test/integration/ResourceAccessTest.java
- northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/ResourceAccessTest.java
- southbound/history/history-api/src/main/java/org/eclipse/sensinact/gateway/southbound/history/api/HistoricalQueries.java
* Detail about how the data model is populated
* Detail about how EMF is used and can be extended
* Detail about how to push updates with generic/custom DTOs
* How to use the whiteboard for action resources, setters and for pull-based GET
> Add more documentation for the data model

- distribution/launcher/src/main/java/org/eclipse/sensinact/gateway/launcher/ConfigurationManager.java
Using the full file paths allows for more thorough checking with the file system and avoids errors where the configuration directory is not the working directory.
> Compare the actual file paths not just the file names

- southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
- southbound/device-factory/parser-json/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/parser/json/JsonRecord.java
- southbound/device-factory/parser-json/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/JSONParserTest.java
- southbound/device-factory/parser-json/src/test/resources/json/multiple-mapping.json
- southbound/device-factory/parser-json/src/test/resources/json/single.json
* The JSON parser now returns long values when the value doesn't fit in an integer
* Added parsed provider name to error message in device factory core
> Fixes for the device factory

- docs/Main.md
- docs/distribution/Distribution.md
- docs/distribution/Launcher.md
- docs/examples/Configuring.md
- docs/examples/Download.md
- docs/examples/Interacting.md
Add some worked examples for the gateway
> Documentation improvements

- southbound/history/timescale-provider/src/main/java/org/eclipse/sensinact/gateway/southbound/history/timescale/TimescaleHistoricalStore.java
- southbound/history/timescale-provider/src/test/java/org/eclipse/sensinact/gateway/southbound/history/timescale/integration/TimescaleHistoryTest.java
* Log errors occurring when preparing tables in the Timescale history provider
* Fixed some errors when restarting the Timescale history provider while tables and extensions already exists
* Integration tests now reuse the same Timescale container to avoid waiting for it to restart between each tests
> History provider enhancement

- core/impl/src/main/java/org/eclipse/sensinact/prototype/model/nexus/emf/compare/EMFCompareUtil.java
- core/impl/src/test/java/org/eclipse/sensinact/prototype/model/nexus/impl/NexusTest.java
If a full provider is pushed and an existing service is replaced by another service it is now possible to "upcast" the Service. This was often the case for providers with special Admin services, which are often created first with a default.
> Services can now be "upgraded"

- docs/source/southbound/mqtt/mqtt-client.md
- southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientConfiguration.java
- southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientHandler.java
- southbound/mqtt/mqtt-client/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/test/MqttAuthTest.java
- southbound/mqtt/mqtt-client/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/test/MqttTest.java
Added support for basic MQTT authentication (username/password) to the MQTT client.
Also updated the documentation.
> Added support for MQTT authentication

- docs/docker-build.sh
We can re-use the Sphinx docker container for faster development. This avoids redownloading and reinstalling apt/python dependencies and cuts the build cycle from 20 seconds to 4 seconds even with a fast internet connection
> Reuse the docs build container for faster development

- southbound/mqtt/mqtt-client/src/main/java/org/eclipse/sensinact/gateway/southbound/mqtt/impl/MqttClientHandler.java
- southbound/mqtt/mqtt-client/src/test/java/org/eclipse/sensinact/gateway/southbound/mqtt/test/MqttDelayedStartTest.java
If the server is not available then we should use the reconnection delay to wait and then reconnect.
> Ensure that the MQTT Client connects to servers eventually

- core/impl/integration-test.bndrun
- core/impl/src/main/java/org/eclipse/sensinact/core/impl/SetValueCommand.java
- core/impl/src/main/java/org/eclipse/sensinact/core/twin/impl/SensinactResourceImpl.java
- core/impl/src/test/java/org/eclipse/sensinact/core/command/impl/WhiteboardImplTest.java
- core/impl/src/test/resources/logback-test.xml
- northbound/filters/ldap/integration-test.bndrun
- northbound/filters/ldap/src/test/resources/logback-test.xml
- northbound/query-handler/integration-test.bndrun
- northbound/query-handler/src/test/resources/logback-test.xml
- northbound/rest/integration-test.bndrun
- northbound/rest/pom.xml
- northbound/rest/src/test/resources/logback-test.xml
- northbound/security/openid-connect/integration-test.bndrun
- northbound/security/openid-connect/src/test/resources/logback-test.xml
- northbound/sensorthings/mqtt/integration-test.bndrun
- northbound/sensorthings/mqtt/pom.xml
- northbound/sensorthings/mqtt/src/test/resources/logback-test.xml
- northbound/sensorthings/rest.gateway/integration-test.bndrun
- northbound/sensorthings/rest.gateway/pom.xml
- northbound/sensorthings/rest.gateway/src/test/resources/logback-test.xml
- northbound/websocket/integration-test.bndrun
- southbound/history/timescale-provider/integration-test.bndrun
- southbound/history/timescale-provider/src/test/resources/logback-test.xml
- southbound/http/http-callback-whiteboard/integration-test.bndrun
- southbound/http/http-callback-whiteboard/src/test/resources/logback-test.xml
- southbound/http/http-device-factory/integration-test.bndrun
- southbound/http/http-device-factory/src/test/resources/logback-test.xml
- southbound/mqtt/mqtt-device-factory/integration-test.bndrun
- southbound/virtual/virtual-temperature-sensor/integration-test.bndrun
- southbound/virtual/virtual-temperature-sensor/src/test/resources/logback-test.xml
Remove warnings and tidy up integration test logging
> Test case improvements

- core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/SensinactWhiteboard.java
- core/impl/src/test/java/org/eclipse/sensinact/core/command/impl/WhiteboardImplTest.java
> Tidy up and fix handling of whiteboard GET calls

- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ProviderSnapshot.java
- core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ProviderSnapshotImpl.java
- core/impl/src/main/java/org/eclipse/sensinact/core/twin/impl/SensinactDigitalTwinImpl.java
- northbound/filters/ldap/src/main/antlr4/org/eclipse/sensinact/northbound/filters/ldap/antlr/LdapFilterLexer.g4
- northbound/filters/ldap/src/main/antlr4/org/eclipse/sensinact/northbound/filters/ldap/antlr/LdapFilterParser.g4
- northbound/filters/ldap/src/main/java/org/eclipse/sensinact/northbound/filters/ldap/antlr/impl/AbstractProviderCriterion.java
- northbound/filters/ldap/src/main/java/org/eclipse/sensinact/northbound/filters/ldap/antlr/impl/CriterionProviderPackageUri.java
- northbound/filters/ldap/src/main/java/org/eclipse/sensinact/northbound/filters/ldap/antlr/impl/FilterVisitor.java
- northbound/filters/ldap/src/test/java/org/eclipse/sensinact/northbound/filters/ldap/LdapParserTest.java
- northbound/filters/ldap/src/test/java/org/eclipse/sensinact/northbound/filters/ldap/integration/LdapFilterTest.java
- northbound/sensorthings/filter/src/test/java/org/eclipse/sensinact/northbound/filters/sensorthings/RcUtils.java
- northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/NotificationSnapshot.java
Allows to filter on the model package URI
> Added a PACKAGE filter criterion

- northbound/session/session-impl/src/main/java/org/eclipse/sensinact/nortbound/session/impl/SensiNactSessionImpl.java
A sensiNact resource scoped bean was used in another scope
> Fixed resource description construction in session

- northbound/gogo-shell/pom.xml
- northbound/gogo-shell/src/main/java/org/eclipse/sensinact/gateway/commands/gogo/ActCommands.java
- northbound/gogo-shell/src/main/java/org/eclipse/sensinact/gateway/commands/gogo/GetCommands.java
- northbound/gogo-shell/src/main/java/org/eclipse/sensinact/gateway/commands/gogo/converter/ResourceTypeConverter.java
* get command converts value to string
* act checks if arguments are known and converts them with OSGi converter
* Added support for more types in ResourceTypeConverter
> Small enhancements of the Gogo shell commands for sensiNact

- core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ServiceSnapshotImpl.java
- core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/ModelNexus.java
- core/impl/src/main/java/org/eclipse/sensinact/core/twin/impl/SensinactDigitalTwinImpl.java
- core/impl/src/main/java/org/eclipse/sensinact/core/twin/impl/SensinactProviderImpl.java
- core/impl/src/test/java/org/eclipse/sensinact/core/model/impl/ModelBuildingTest.java
- core/impl/src/test/java/org/eclipse/sensinact/core/twin/impl/SensinactTwinTest.java
... else services when no value was explicitly set are not snapshotted
> Fix to list services and resources on newly created provider instances

- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ProviderSnapshot.java
- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ResourceSnapshot.java
- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ServiceSnapshot.java
- core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ProviderSnapshotImpl.java
- core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ResourceSnapshotImpl.java
- core/impl/src/main/java/org/eclipse/sensinact/core/impl/snapshot/ServiceSnapshotImpl.java
- northbound/filters/ldap/src/test/java/org/eclipse/sensinact/northbound/filters/ldap/LdapParserTest.java
- northbound/sensorthings/filter/src/test/java/org/eclipse/sensinact/northbound/filters/sensorthings/RcUtils.java
- northbound/sensorthings/mqtt/src/main/java/org/eclipse/sensinact/gateway/northbount/sensorthings/mqtt/SensorthingsMapper.java
- northbound/websocket/src/main/java/org/eclipse/sensinact/northbound/ws/impl/NotificationSnapshot.java
Added utility methods to ease handling of snapshots
> Snapshot API enhancement

- northbound/query-handler/src/main/java/org/eclipse/sensinact/northbound/query/impl/QueryHandler.java
- northbound/query-handler/src/test/java/org/eclipse/sensinact/northbound/query/test/integration/DescriptionsTest.java
Metadata were never added to the resource description.
Exclude timestamp as it is associated to resource value (GET)
> Fixed inclusion of metadata in resource description

- southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
- southbound/device-factory/device-factory-core/src/test/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/RecordHandlingTest.java
Device factory mapping now support metadata: `service/resource/metadata` is now a valid path.
For example:
```json
"mapping": {
"data/value": "value",
"data/value/unit": "unit",
"data/value/precision": {
"literal": 3
}
}
```
> Added support for resource metadata in device factory

- southbound/device-factory/device-factory-core/src/main/java/org/eclipse/sensinact/gateway/southbound/device/factory/impl/FactoryParserHandler.java
Avoids setting the value to null while updating the metadata
> Mark metadata DTOs with NullAction.IGNORE

- core/impl/src/main/java/org/eclipse/sensinact/core/extract/impl/AnnotationMapping.java
- core/impl/src/test/java/org/eclipse/sensinact/core/extract/impl/AnnotationBasedDtoExtractorTest.java
String fields annotated with @Resource and @Metadata caused all mappings to use the metadata value as the mapping. This should not happen!
> Annotated DTO mapping error

- core/impl/src/main/java/org/eclipse/sensinact/core/whiteboard/impl/SensinactWhiteboard.java
* Added logs and return a failed promise when an error occurs when creating/updating a model
* Check if a model exists using both the package URI and model name
> Whiteboard: fixed model creation/update

- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ICriterion.java
- core/api/src/main/java/org/eclipse/sensinact/core/snapshot/ICriterionSupport.java
- core/api/src/test/java/org/eclipse/sensinact/core/snapshot/ICriterionTest.java
- southbound/rules/rules.impl/src/main/java/org/eclipse/sensinact/southbound/rules/impl/RuleProcessor.java
- southbound/rules/rules.impl/src/test/java/org/eclipse/sensinact/southbound/rules/impl/integration/RulesWhiteboardIntegrationTest.java
* Add logging when a rules notification throws an exception
* Prevent NPE when using a ResourceValueFilter from an ICriterion
> Fix a bug identified when using Rules

- core/emf-api/dependency-check.bndrun
- core/impl/integration-test.bndrun
- core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/emf/EMFUtil.java
- distribution/features/core-feature/src/main/resources/core-feature.json
- filters/ldap/integration-test.bndrun
- filters/resource.selector.impl/integration-test.bndrun
- northbound/query-handler/integration-test.bndrun
- northbound/rest/integration-test.bndrun
- northbound/security/openid-connect/integration-test.bndrun
- northbound/sensorthings/mqtt/integration-test.bndrun
- northbound/sensorthings/rest.gateway/integration-test.bndrun
- northbound/session/session-impl/integration-test.bndrun
- northbound/websocket/integration-test.bndrun
- pom.xml
- southbound/history/timescale-provider/integration-test.bndrun
- southbound/http/http-callback-whiteboard/integration-test.bndrun
- southbound/http/http-device-factory/integration-test.bndrun
- southbound/mqtt/mqtt-device-factory/integration-test.bndrun
- southbound/rules/easy-rules/config/integration-test.bndrun
- southbound/rules/easy-rules/osgi/integration-test.bndrun
- southbound/rules/rules.impl/integration-test.bndrun
- southbound/virtual/virtual-temperature-sensor/integration-test.bndrun
Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>
> updated geckoemf to 6.3

- southbound/wot/api/src/main/java/org/eclipse/sensinact/gateway/southbound/wot/api/dataschema/DataSchema.java
- southbound/wot/api/src/main/java/org/eclipse/sensinact/gateway/southbound/wot/api/dataschema/DataSchemaTypeResolver.java
- southbound/wot/api/src/main/java/org/eclipse/sensinact/gateway/southbound/wot/api/dataschema/OneOfDataSchema.java
- southbound/wot/api/src/main/java/org/eclipse/sensinact/gateway/southbound/wot/api/dataschema/UnknownDataTypeSchema.java
- southbound/wot/api/src/test/java/org/eclipse/sensinact/gateway/southbound/wot/test/ParserTest.java
- southbound/wot/api/src/test/resources/data/dataschema-test.jsonld
Added support for unknown types and oneOf-only data schema
> Enhanced support for WoT type namings

- .github/workflows/eclipse_ip.yml
- .licenserc.yaml
- DEPENDENCIES
- README.md
- pom.xml
Use Dash to generate the dependencies file, and update the README to talk about the structure of the build.
Prepares for alpha release #549
> Automate generation of the DEPENDENCIES file

- filters/resource.selector.impl/src/main/java/org/eclipse/sensinact/filters/resource/selector/impl/ResourceSelectorCriterion.java
- filters/resource.selector.impl/src/test/java/org/eclipse/sensinact/filters/resource/selector/impl/ResourceSelectorTest.java
- filters/resource.selector/src/main/java/org/eclipse/sensinact/filters/resource/selector/api/ValueSelection.java
Only works for EQUALS and NOT_EQUALS
> Allow ResourceSelector to compare null values

- core/impl/src/main/java/org/eclipse/sensinact/core/model/nexus/emf/compare/EMFCompareUtil.java
- core/impl/src/test/java/org/eclipse/sensinact/core/integration/EMFUpdateServiceTest.java
@juergen-albert has accidentally deleted the handling of the metadata.
> revert deleted timestamp handling

- docs/source/northbound/RestDataAccess.md
- northbound/rest/pom.xml
- northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/BundleDTO.java
- northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestAccessApplication.java
- northbound/rest/src/main/java/org/eclipse/sensinact/northbound/rest/impl/RestRuntime.java
- northbound/rest/src/test/java/org/eclipse/sensinact/northbound/rest/integration/RestRuntimeTest.java
This makes it easier to check all osgi bundle versions.
The endpoint returns the list of all osgi bundles, along with their name, version, git-ref, git-sha.
> Add a versions rest endpoint
